### ISSUE TITLE
[Bug]Named export 'theme' not found. The requested module '@chakra-ui/react'

### ISSUE THREAD

**Issue by octalpixel** [saas-js/saas-ui#47] opened 2022-06-02 18:36 UTC
Came across the issue using the "@saas-ui/react": "^1.0.0-rc.3" on next.js. 

The ideal step to reproduce would be to install @chakra/react v2 and the RC release of @saas-ui
Edit: [This is a nx monorepo](https://github.com/saas-js/saas-ui/issues/47#issuecomment-1145270833)

![image](https://user-images.githubusercontent.com/30002284/171701646-20f5d479-6bc2-4e9a-9a86-bab1d66b7d26.png)

**Comment by Pagebakers** [comment] 2022-06-02 19:33
Thanks for reporting!

Can you share your next.config.js please?

**Comment by Pagebakers** [comment] 2022-06-02 19:44
I created a new project yesterday with Next 12.6, Chakra 2.1 and Saas UI 1.0.0-rc.3 and it's working perfectly, tried again just now without issues.

Might be NX related, I'll try to add it to the project and see what happens :)

**Comment by Pagebakers** [comment] 2022-06-02 20:13
Ok did get it running just now with nx.

Not having any issues, not sure how to reproduce your issue.

```
import { AppProps } from 'next/app';
import Head from 'next/head';
import './styles.css';

import { SaasProvider, theme } from '@saas-ui/react';
import { Container } from '@chakra-ui/react';

function CustomApp({ Component, pageProps }: AppProps) {
  return (
    <SaasProvider theme={theme}>
      <Head>
        <title>Welcome to blog-nx!</title>
      </Head>
      <Container>
        <Component {...pageProps} />
      </Container>
    </SaasProvider>
  );
}

export default CustomApp;
```

```
{
  "name": "blog-nx",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "dependencies": {
    "@emotion/react": "11.9.0",
    "@emotion/server": "11.4.0",
    "@emotion/styled": "11.8.1",
    "@chakra-ui/react": "^2.1.2",
    "@saas-ui/react": "1.0.0-rc.3",
    "framer-motion": "^6",
    "@nrwl/next": "14.1.9",
    "core-js": "^3.6.5",
    "next": "12.1.5",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "regenerator-runtime": "0.13.7",
    "tslib": "^2.3.0"
  },
  "devDependencies": {
    "@emotion/babel-plugin": "11.9.2",
    "@nrwl/cli": "14.1.9",
    "@nrwl/cypress": "14.1.9",
    "@nrwl/eslint-plugin-nx": "14.1.9",
    "@nrwl/jest": "14.1.9",
    "@nrwl/linter": "14.1.9",
    "@nrwl/react": "14.1.9",
    "@nrwl/web": "14.1.9",
    "@nrwl/workspace": "14.1.9",
    "@testing-library/react": "13.1.1",
    "@types/jest": "27.4.1",
    "@types/node": "16.11.7",
    "@types/react": "18.0.8",
    "@types/react-dom": "18.0.3",
    "@typescript-eslint/eslint-plugin": "~5.18.0",
    "@typescript-eslint/parser": "~5.18.0",
    "babel-jest": "27.5.1",
    "cypress": "^9.1.0",
    "eslint": "~8.12.0",
    "eslint-config-next": "12.1.5",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jsx-a11y": "6.5.1",
    "eslint-plugin-react": "7.29.4",
    "eslint-plugin-react-hooks": "4.5.0",
    "jest": "27.5.1",
    "nx": "14.1.9",
    "prettier": "^2.5.1",
    "react-test-renderer": "18.1.0",
    "ts-jest": "27.1.4",
    "ts-node": "9.1.1",
    "typescript": "~4.6.2"
  }
}

``

**Comment by Pagebakers** [comment] 2022-06-02 20:17
I had similar issues as you with Storybook and had to add this to the webpack config.

```js
    config.module.rules.push({
      test: /\.mjs$/,
      include: /node_modules/,
      type: 'javascript/auto',
    })
```

**Comment by octalpixel** [comment] 2022-06-02 22:23
Thanks @Pagebakers for looking into it and for the examples. Let me try for suggestions and see if I can fix it.

**Comment by Pagebakers** [comment] 2022-06-03 07:52
Let me know how it goes.

**Comment by Pagebakers** [comment] 2022-06-06 20:29
@octalpixel Did you get it running?

**Comment by octalpixel** [comment] 2022-06-08 03:48
Hey! Not yet, I went with only chakra for now. But will be revisiting this.

**Comment by Pagebakers** [comment] 2022-06-15 14:46
Closing this for now, happy to help you out when you get back to it!

**Comment by msnegurski** [comment] 2022-08-06 13:56
Had same error, tried to recreate it and it happens on fresh NextJS install. Here is a repo: https://github.com/msnegurski/test-saas-ui

**Comment by Pagebakers** [comment] 2022-08-06 14:33
Thanks @msnegurski I will look into it!

**Comment by Pagebakers** [comment] 2022-08-06 15:20
I'm able to reproduce it finally :)

Next.js fails to resolve to the Chakra UI module correctly, from the Saas UI esm module.

This only happens in JS mode, in TypeScript this doesn't happen it seems.

**Comment by Pagebakers** [comment] 2022-08-06 15:50
The problem is the exports definition in the Saas UI packages.

```
  "exports": {
    ".": {
      "require": "./dist/index.js",
      "default": "./dist/index.modern.mjs"
    }
  },
  ```

Next.js is tripping over this and fails to resolve sub packages incorrectly. Changing `default` to `import` fixes the issue. I'm not sure if this is supposed to work like this, or if this is a bug in Next, but I suspect the latter.

I'll release an update asap.

The work around for now is to use Typescript.

**Comment by msnegurski** [comment] 2022-08-06 16:11
I guess time to migrate to typescript. Thanks for the update!

**Comment by Pagebakers** [comment] 2022-08-06 16:32
I opened an issue at next.

https://github.com/vercel/next.js/issues/39375

**Comment by Pagebakers** [comment] 2022-08-06 18:24
Released @saas-ui/react@1.3.1 and @saas-ui/pro@0.7.0 with updated exports definitions.

This fixed it for me.

**Comment by msnegurski** [comment] 2022-08-07 08:38
Yes, that fixed it, thank you! Though I am now getting similar error when use pro components like AppShell, Page, Section:

> SyntaxError: Named export 'getStateColors' not found. The requested module '@saas-ui/theme' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from '@saas-ui/theme';
> const { getStateColors } = pkg;

**Comment by Pagebakers** [comment] 2022-08-07 08:41
Interesting, I implemented the same fix in @saas-ui/pro@0.7.0

Let me test this again.

**Comment by msnegurski** [comment] 2022-08-07 08:42
Here is a repo https://github.com/msnegurski/test-next-typescript

**Comment by Pagebakers** [comment] 2022-08-07 09:17
.mjs files are causing the issues, I renamed everything to .js to resolve the issue for now.

**Closed by Pagebakers** 2022-08-07 09:17 UTC

**Comment by tecoad** [comment] 2022-08-07 13:28
@Pagebakers arrived here from Google. I don't use Saas-ui but I do use:

```
    "@chakra-ui/icons": "^2.0.1",
    "@chakra-ui/pro-theme": "^0.0.53",
    "@chakra-ui/react": "^2.0.2",
    "@chakra-ui/theme": "^2.0.1",
    "@chakra-ui/theme-tools": "^2.0.0",
    "next": "12.1.6",
```

This issue started suddently yesterday in my project and happens only when I use the pro-theme into extendTheme().

Quite don't understand why is the bug, since I didn't update anything.  Should be an issue with chakra, actually?

Btw, Love saas-ui, will try!

**Comment by Pagebakers** [comment] 2022-08-07 13:31
@tecoad Can you share your error? then we can have a better idea if this is really the same issue.

And please do, love to hear your feedback 👌

**Comment by Pagebakers** [comment] 2022-08-07 13:36
Interesting, this issue is the same, I just checked the pro-theme source code and it is using .mjs extension too. 

Please upvote and share your issues on the Next issue that I've opened

> I opened an issue at next.
> 
> [vercel/next.js#39375](https://github.com/vercel/next.js/issues/39375)

**Comment by tecoad** [comment] 2022-08-07 13:59
@Pagebakers Here is my log:

```
info  - Collecting page data .node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

file:///Users/matheus/Desktop/project/app/node_modules/@chakra-ui/pro-theme/dist/index.mjs:20
import { extendTheme, theme as theme$1 } from "@chakra-ui/react";
                      ^^^^^
SyntaxError: Named export 'theme' not found. The requested module '@chakra-ui/react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@chakra-ui/react';
const { extendTheme, theme: theme$1 } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15) {
  type: 'SyntaxError'
}
```

I haven't upgraded nextjs recently... which is odd.

**Comment by Pagebakers** [comment] 2022-08-07 14:17
Thats odd indeed! This might have been around for awhile though.

Are you using typescript?

**Comment by tecoad** [comment] 2022-08-07 14:26
Yes, im using TS.

**Comment by Pagebakers** [comment] 2022-08-07 14:38
Odd, i didnt have the problem in ts projects. 

What package manager do you use

**Comment by tecoad** [comment] 2022-08-07 14:53
@Pagebakers , using yarn

Here is a minimal case I was able to reproduce the same error, if it helps:
https://github.com/tecoad/my-app

I will submit this to chakra aswell.

**Comment by tecoad** [comment] 2022-08-07 14:57
https://github.com/chakra-ui/chakra-ui/issues/6436

**Comment by Pagebakers** [comment] 2022-08-07 15:12
Can you try setting this to true or  false in next.config.js and see if that resolves anything?

```experimental.esmExternals: false```

**Comment by Pagebakers** [comment] 2022-08-07 15:17
Ok I can confirm setting it to false is working here. But obviously not a solution, because it'll use CJS instead of ESM.. ;/

**Comment by tecoad** [comment] 2022-08-07 17:22
Same here. Not a solution indeed.

**Comment by tecoad** [comment] 2022-08-07 19:46
@Pagebakers been seeing the Saas-ui docs, seems very promising. Is there any demo boilerplate where we can see any fully working example? The components are great, but would be nicer to see how the can come together.

Regards,

**Comment by Pagebakers** [comment] 2022-08-07 20:01
Here is a live demo, but the complete boilerplate is only available in Pro at the moment.

https://demo.saas-ui.dev
